name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Publicar projeto
        run: dotnet publish "VisualizadorDeResultadosBolão/VisualizadorDeResultadosBolão.csproj" -c Release -o release

      - name: Corrigir base href
        run: sed -i 's|<base href="/" />|<base href="/VisualizadorDeResultados/" />|g' release/wwwroot/index.html

      - name: Criar arquivo 404
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: release/wwwroot

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4